/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitesAcceptRouteImport } from './routes/invites.accept'

const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesAcceptRoute = InvitesAcceptRouteImport.update({
  id: '/invites/accept',
  path: '/invites/accept',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/invites/accept': typeof InvitesAcceptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/invites/accept': typeof InvitesAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/invites/accept': typeof InvitesAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/device' | '/invites/accept'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/device' | '/invites/accept'
  id: '__root__' | '/' | '/device' | '/invites/accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeviceRoute: typeof DeviceRoute
  InvitesAcceptRoute: typeof InvitesAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/accept': {
      id: '/invites/accept'
      path: '/invites/accept'
      fullPath: '/invites/accept'
      preLoaderRoute: typeof InvitesAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeviceRoute: DeviceRoute,
  InvitesAcceptRoute: InvitesAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
