import { defineConfig } from 'vite-plus'

export default defineConfig({
  fmt: {
    // CHANGELOG.md files are generated by @changesets/changelog-github, which
    // emits a blank line per entry that oxfmt strips — so a freshly versioned
    // main would always fail `vp check`. They are machine-generated; don't
    // format them.
    ignorePatterns: ['**/dist/**', '**/CHANGELOG.md'],
    singleQuote: true,
    semi: false,
    printWidth: 100,
  },
  lint: {
    ignorePatterns: ['**/dist/**', 'scripts/**', 'apps/worker/tests/**'],
    options: { typeAware: true, typeCheck: true },
  },
  test: {
    projects: ['packages/*', 'apps/cli', 'apps/worker'],
  },
})
